# action.yml
name: 'Send files'
description: 'Copy folder with ftp to server'
inputs:
  ftp_domain:  # id of input
    description: 'The domain name of the website'
    required: true
  ftp_host:
    description: 'The host name of the provider'
    required: true
  source:
    description: 'Path to the source folder'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ftp_domain }}
    - ${{ inputs.ftp_host }}
    - ${{ inputs.source }}
