# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  ftp-domain:  # id of input
    description: 'The domain name of the website'
    required: true
  ftp-host:
    description: 'The host name of the provider'
    required: true
  source:
    description: 'Path to the source folder'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.ftp-domain }}
    - ${{ inputs.ftp-host }}
    - ${{ inputs.source }}
